#### Sentiment analysis 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [4]:
from sklearn import svm

In [5]:
from sklearn.cross_validation import train_test_split

In [6]:
def readConHandles():
    prueba=pd.read_csv('everything.csv')
    labels=prueba[['Label']].convert_objects(convert_numeric=True)
    data=prueba[['Tweet']]
    handles=prueba[['Handle']]
    labelsList=labels['Label'].fillna(0).values.tolist()
    dataList=prueba['Tweet'].values.tolist()
    lista=prueba['Handle'].values.tolist()
    nueva=[]
    for i in range(len(lista)):
        nueva.append(lista[i]+' '+dataList[i])
    return nueva, labelsList
    #esto hace que los handles sean la primera "palabra" del string para la bag of words para que sean tomados en cuenta 
    #(esto va a hacer todo mil mas larga y no se si vaya a valer la pena)

In [50]:
def read():
    prueba=pd.read_csv('everythingEVEN.csv')
    labels=prueba[['Label']].convert_objects(convert_numeric=True)
    data=prueba[['Tweet']]
    handles=prueba[['Handle']]
    labelsList=labels['Label'].fillna(0).values.tolist()
    dataList=prueba['Tweet'].values.tolist()
    lista=prueba['Handle'].values.tolist()
    return dataList, labelsList

In [7]:
dataList, labelsList=readConHandles()

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()


In [72]:
erroresTodos(expectedL[1],predictedL[1]) #01 02 10 12 20 21

(104, 2, 52, 0, 28, 108)

In [8]:
vectorizer = CountVectorizer(stop_words='english',min_df=1)
X = vectorizer.fit_transform(dataList)

In [77]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),stop_words='english',
                                     token_pattern=r'\b\w+\b', min_df=1)
X2=vectorizer.fit_transform(dataList)

In [9]:
X_train, X_test, trainLabels, testLabels = train_test_split(X.toarray(), labelsList, test_size=0.75)

In [14]:
clf = svm.SVC(kernel='poly')
clf.fit(X_train, trainLabels)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
svmPred=clf.predict(X_test)

In [16]:
expected = testLabels
print(metrics.accuracy_score(expected, svmPred))
print(metrics.confusion_matrix(expected, svmPred))

0.821565044027
[[   0    0  447]
 [   0    0  627]
 [   0    0 4945]]


In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_blobs

In [20]:
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=1,
     random_state=0)
#scores = cross_val_score(clf, X, y)
clf.fit(X_train, trainLabels) 
predicted = clf.predict(X_test)
print(metrics.accuracy_score(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

0.893836185413
[[ 253   42  152]
 [  51  300  276]
 [  26   92 4827]]


In [36]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None,
     min_samples_split=1, random_state=0)


In [37]:
clf.fit(X_train, trainLabels)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=1,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [38]:
predicted = clf.predict(X_test)


In [22]:
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
     min_samples_split=1, random_state=0)
clf.fit(X_train, trainLabels)
predicted = clf.predict(X_test)
print(metrics.accuracy_score(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

0.891177936534
[[ 199   16  232]
 [  24  248  355]
 [   3   25 4917]]


In [33]:
expectedL=[]
predictedL=[]
scoreL=[]
conf=np.zeros((3, 3))
for i in range(10+1):
    X_train, X_test, trainLabels, testLabels = train_test_split(X.toarray(), labelsList, test_size=0.75)
    #model=MultinomialNB()
    #model.fit(X_train, trainLabels)
    expected = testLabels
    #predicted = model.predict(X_test)
    #clf = DecisionTreeClassifier(max_depth=None, min_samples_split=1)
    #clf = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=1)
    clf = DecisionTreeClassifier(max_depth=None, min_samples_split=1)
    clf.fit(X_train, trainLabels) 
    predicted = clf.predict(X_test)
    expectedL.append(expected)
    predictedL.append(predicted)
    scoreL.append(metrics.accuracy_score(expected, predicted))
    conf+=metrics.confusion_matrix(expected, predicted)
    #print(metrics.accuracy_score(expected, predicted))
    #print(metrics.classification_report(expected, predicted))
    #print(metrics.confusion_matrix(expected, predicted))

In [34]:
np.mean(scoreL)

0.89750638130767724

In [35]:
conf/10

array([[  307.3,    53.6,   106.8],
       [   77.7,   347.5,   252.9],
       [   59.5,   128.1,  5287.5]])

In [ ]:
baseline=[random.randint(0,2) for i in range(len(predicted))]
print(metrics.accuracy_score(expected, baseline))
print(metrics.confusion_matrix(expected, baseline))